<?php
return array (
  'contents' => 
  array (
    0 => 
    array (
      'fieldid' => '43',
      'modelid' => '7',
      'field' => 'type',
      'name' => '类型',
      'tips' => '图片|视频|全景图',
      'css' => '',
      'minlength' => '1',
      'maxlength' => '100',
      'errortips' => '',
      'fieldtype' => 'select',
      'defaultvalue' => '全景图',
      'setting' => '{\\"0\\":\\"\\\\u56fe\\\\u7247\\",\\"1\\":\\"\\\\u89c6\\\\u9891\\",\\"2\\":\\"\\\\u5168\\\\u666f\\\\u56fe\\",\\"3\\":\\"\\\\u8003\\\\u9898\\"}',
      'isrequired' => '1',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    1 => 
    array (
      'fieldid' => '44',
      'modelid' => '7',
      'field' => 'image',
      'name' => '图片',
      'tips' => '',
      'css' => '',
      'minlength' => '0',
      'maxlength' => '100',
      'errortips' => '',
      'fieldtype' => 'image',
      'defaultvalue' => '',
      'setting' => '',
      'isrequired' => '0',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    2 => 
    array (
      'fieldid' => '45',
      'modelid' => '7',
      'field' => 'music',
      'name' => '背景音乐',
      'tips' => '',
      'css' => '',
      'minlength' => '0',
      'maxlength' => '100',
      'errortips' => '',
      'fieldtype' => 'attachment',
      'defaultvalue' => '',
      'setting' => '',
      'isrequired' => '0',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    3 => 
    array (
      'fieldid' => '46',
      'modelid' => '7',
      'field' => 'video',
      'name' => '视频',
      'tips' => '',
      'css' => '',
      'minlength' => '0',
      'maxlength' => '100',
      'errortips' => '',
      'fieldtype' => 'attachment',
      'defaultvalue' => '',
      'setting' => '',
      'isrequired' => '0',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    4 => 
    array (
      'fieldid' => '47',
      'modelid' => '7',
      'field' => 'viewurl',
      'name' => '全景图',
      'tips' => '',
      'css' => '',
      'minlength' => '0',
      'maxlength' => '100',
      'errortips' => '',
      'fieldtype' => 'input',
      'defaultvalue' => '',
      'setting' => '',
      'isrequired' => '0',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '1',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
    5 => 
    array (
      'fieldid' => '49',
      'modelid' => '7',
      'field' => 'shiti',
      'name' => '试题',
      'tips' => '',
      'css' => '',
      'minlength' => '0',
      'maxlength' => '255',
      'errortips' => '',
      'fieldtype' => 'input',
      'defaultvalue' => '',
      'setting' => NULL,
      'isrequired' => '0',
      'issystem' => '0',
      'isunique' => '0',
      'isadd' => '0',
      'listorder' => '1',
      'disabled' => '0',
      'type' => '0',
      'status' => '1',
    ),
  ),
  'expire' => 0,
  'mtime' => 1590736880,
);
?>